<?xml version="1.0"?>

<robot  xmlns:xacro ="http://www.ros.org/wiki/xacro" >

<xacro:property name="base_len" value="0.6" />
<xacro:property name="base_width" value="0.4" />
<xacro:property name="base_height" value="0.2" />



<!--wheel-->
<xacro:property name="wheel_r" value="0.08" />
<xacro:property name="wheel_len" value="0.05" />



<!--base link-->

<link name="base_footprint"/>


  <!-- Base -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_len} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0.0 0.0 ${base_height/2}" rpy="0 0 0"/>  <!-- Fixed height -->
      <material name="green"/>
    </visual>
    <collision>
        <geometry>
            <box size="${base_len} ${base_width} ${base_height}"/>
        </geometry>
      <origin xyz="0.0 0.0 ${base_height/2}" rpy="0 0 0"/>  <!-- Match visual origin -->
   </collision>
   <xacro:box_inertia m="0.5" x="${base_len}" y="${base_width}" z="${base_height}" o_xyz="0 0 ${base_height/2}" o_rpy="0 0 0"/>

  </link>




<joint name="base_joint" type="fixed">
    <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

  <!-- ================= Wheels ================= -->

  <xacro:macro name="wheel_link" params ="prefix">
    <link name="wheel_${prefix}">
    <visual>
      <geometry>
        <cylinder radius="${wheel_r}" length="${wheel_len}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/> <!-- rotate cylinder to stand as wheel -->
      <material name="black"/>



    </visual>

    <collision>
      <geometry>
        <cylinder radius="${wheel_r}" length="${wheel_len}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
    </collision>
    <xacro:cylinder_inertia m="0.5" r="${wheel_r}" h="${wheel_len}" o_xyz="0 0 0" o_rpy="1.5708 0 0"/>
  </link>
  </xacro:macro>



  <xacro:macro name="wheel_joint" params="prefix x_pos y_pos">
    <joint name="joint_wheel_${prefix}" type="continuous">
      <parent link="base_link"/>
      <child link="wheel_${prefix}"/>
      <origin xyz="${x_pos} ${y_pos} -${base_height/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Front Left Wheel -->
  <xacro:wheel_link prefix="fl"/>
  <xacro:wheel_joint prefix="fl" x_pos="${(base_len/4)+0.1}" y_pos="${base_width/2}"/>

  <!-- Front Right Wheel -->
  <xacro:wheel_link prefix="fr"/>
  <xacro:wheel_joint prefix="fr" x_pos="${(base_len/4)+0.1}" y_pos="-${base_width/2}"/>

  <!-- Rear Left Wheel -->
  <xacro:wheel_link prefix="rl"/>
  <xacro:wheel_joint prefix="rl" x_pos="-${(base_len/4)+0.1}" y_pos="${base_width/2}"/>

  <!-- Rear Right Wheel -->
  <xacro:wheel_link prefix="rr"/>
  <xacro:wheel_joint prefix="rr" x_pos="-${(base_len/4)+0.1}" y_pos="-${base_width/2}"/>


  <!--Camera-->
  <link name="cam">
    <visual>
        <geometry>
            <box size="0.04 0.06 0.08"/>
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </visual>
    <collision>
        <geometry>
            <box size="0.04 0.06 0.08"/>
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </collision>
    <xacro:box_inertia m="0.1" x="0.04" y="0.06" z="0.08" o_xyz="0 0 0" o_rpy="0 0 0"/>
  </link>

  <joint name="joint_cam" type="fixed">
    <parent link="base_link"/>
    <child link="cam"/>
    <origin xyz="${base_len/2 - 0.02} 0.0 ${base_height/2 + 0.04}" rpy="0.0 0.0 0.0"/>
  </joint>

  <!-- Material definitions are in material.xacro -->

  <!-- Add Gazebo material colors -->
  <gazebo reference="base_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <gazebo reference="wheel_fl">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="wheel_fr">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="wheel_rl">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="wheel_rr">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="cam">
        <material>Gazebo/Blue</material>
    </gazebo>
</robot>